### ISSUE TITLE
DailyLife 프론트 및 기본 세팅

### ISSUE THREAD

**Issue by ykp9711** [ykp9711/Project_DailyLife#1]
1. 로그인 , 회원가입 , 아이디, 비밀번호 찾기 프론트 구현
2. 메인페이지 구현
3. 헤더구현 ( 좋아요 알람설정 페이지 , 게시글 등록 , 내 정보)
4. 게시글 등록 및 게시글 상세보기 프론트 구현
5. 내정보 및 내정보 수정 프론트 구현
6. 채팅(DM) 프론트 구현

**Comment by wjdrms5815** [comment]
wow !!

**Comment by wjdrms5815** [comment]
테스트 성공

**Comment by ykp9711** [comment]
![2 - 복사본 (3)](https://user-images.githubusercontent.com/62640768/157597096-899ddccb-5f3a-4290-b023-f158fbdc8264.png)

기능2

**Comment by ykp9711** [comment]
commit 5b6a2

**Comment by ykp9711** [comment]
commit 5b6a2

**Comment by ykp9711** [comment]
commit 5b6a21d
